# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "merged-api"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "merged-api"
region = "us-east-2"
profile = "default"
image_repositories = []
parameter_overrides = "CarApiId=\"5ejbyfyiavg3lbkrcgfalz2hje\" RentApiId=\"gfb4mpoyunavzlmcv6iv2ngyv4\" UserPoolId=\"us-east-2_HREKK4JXw\" UserPoolIdRegion=\"us-east-2\""

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
