version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "user-merged-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w7fazjv91dr3"
s3_prefix = "user-merged-api"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ClientDomain=\"https:my.carapp.com\" Env=\"dev\" TechStack=\"graphql\""
image_repositories = []
