AWSTemplateFormatVersion: 2010-09-09
Description: >-
  car-app
Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: nodejs16.x
    CodeUri: src/
    Tracing: Active
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: ecom-app
        LOG_LEVEL: INFO
        POWERTOOLS_METRICS_NAMESPACE: ecom-app-metric

  Api:
    TracingEnabled: True

Parameters:
  ClientDomain:
    Type: String
    Description: Domain allowed to use this UserPool
  Env:
    Type: String
    Description: Environnement name
    Default: dev
  TechStack:
    Type: String
    Description: Framework used or resource used.
    Default: graphql


Resources:


  UserPool:
    Type: AWS::Cognito::UserPool 
    Properties:
      UserPoolName: !Sub userpool-app-${TechStack}-${Env}
      Policies: 
        PasswordPolicy: 
          MinimumLength: 8
      AutoVerifiedAttributes:
        - email
      UsernameAttributes: 
        - email
      Schema: 
        - AttributeDataType: String 
          Name: email 
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: address
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: birthdate
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: gender
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: family_name
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: given_name
          Required: true

  # Create an application for authentication
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient 
    Properties: 
      ClientName: !Sub userpool-${TechStack}-${Env}
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !Ref ClientDomain
      LogoutURLs:
        - !Ref ClientDomain
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
  
    # Create a hosted domain for users to signup and login
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain: graphqlauth-car
      UserPoolId: !Ref UserPool



# Outputs:
#   WebEndpoint:
#     Description: API Gateway endpoint URL for Prod stage
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
# # More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
