AWSTemplateFormatVersion: 2010-09-09
Description: >-
  auth-app
Transform:
- AWS::Serverless-2016-10-31

Parameters:
  ClientDomain:
    Type: String
    Description: Domain allowed to use this UserPool
  Env:
    Type: String
    Description: Environnement name
    Default: dev
  TechStack:
    Type: String
    Description: Framework used or resource used.
    Default: graphql


Resources:


  UserPool:
    Type: AWS::Cognito::UserPool 
    Properties:
      UserPoolName: !Sub userpool-app-${TechStack}-${Env}
      Policies: 
        PasswordPolicy: 
          MinimumLength: 8
      AutoVerifiedAttributes:
        - email
      UsernameAttributes: 
        - email
      Schema: 
        - AttributeDataType: String 
          Name: email 
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: address
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: birthdate
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: gender
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: family_name
          Required: true
        - AttributeDataType: String
          Mutable: true
          Name: given_name
          Required: true

  # Create an application for authentication
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient 
    Properties: 
      ClientName: !Sub userpool-${TechStack}-${Env}
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - !Ref ClientDomain
      LogoutURLs:
        - !Ref ClientDomain
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
  
    # Create a hosted domain for users to signup and login
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties: 
      Domain: graphqlauth-car
      UserPoolId: !Ref UserPool



Outputs:
  UserPoolId:
    Description: "User pool ID"
    Value: !Ref UserPool

  UserPoolClientId:
    Description: "Application client ID"
    Value: !Ref UserPoolClient

  AuthUrl:
    Description: "URL used for authentication"
    Value: !Sub https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/login
    
  Issuer:
    Description: "Url used for issuer on HTTP API JWT tokens"
    Value: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}