AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Car Graphql API

  '
Globals:
  Api:
    TracingEnabled: true
Parameters:
  Env:
    Type: String
    Description: Environnement name
    Default: dev
  TechStack:
    Type: String
    Description: Framework used or resource used.
    Default: graphql
  UserPoolId:
    Type: String
    Description: User pool Id
  UserPoolIdRegion:
    Type: String
    Description: User pool id region
Resources:
  AppSyncServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - appsync.amazonaws.com
          Action:
          - sts:AssumeRole
  CarApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: CarApi
      AuthenticationType: API_KEY
      AdditionalAuthenticationProviders:
      - AuthenticationType: AMAZON_COGNITO_USER_POOLS
        UserPoolConfig:
          UserPoolId:
            Ref: UserPoolId
          AwsRegion:
            Ref: UserPoolIdRegion
      XrayEnabled: true
  CarApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
  CarApiSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
      DefinitionS3Location: ../../schema.graphql
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
          - W3002
  CarTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: Car-${TechStack}-${Env}
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  CarDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
      Name: CarDatascource
      Type: AMAZON_DYNAMODB
      ServiceRoleArn:
        Fn::GetAtt:
        - AppSyncServiceRole
        - Arn
      DynamoDBConfig:
        AwsRegion:
          Ref: AWS::Region
        TableName:
          Ref: CarTable
  CreateCarFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
      CodeS3Location: ./src/handlers/put-item.mjs
      DataSourceName:
        Fn::GetAtt:
        - CarDataSource
        - Name
      Description: Creata a car
      FunctionVersion: '2018-05-29'
      Name: createcar
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
  UpdateCarFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
      CodeS3Location: ./src/handlers/update-item.mjs
      DataSourceName:
        Fn::GetAtt:
        - CarDataSource
        - Name
      Description: Update a car
      FunctionVersion: '2018-05-29'
      Name: updatecar
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
  GetCarFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
      CodeS3Location: ./src/handlers/get-by-id.mjs
      DataSourceName:
        Fn::GetAtt:
        - CarDataSource
        - Name
      Description: Get by id a car
      FunctionVersion: '2018-05-29'
      Name: getcar
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
  ListCarFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
      CodeS3Location: ./src/handlers/get-all-items.mjs
      DataSourceName:
        Fn::GetAtt:
        - CarDataSource
        - Name
      Description: Get all cars
      FunctionVersion: '2018-05-29'
      Name: listcar
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
  DeleteCarFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
      CodeS3Location: ./src/handlers/delete-item.mjs
      DataSourceName:
        Fn::GetAtt:
        - CarDataSource
        - Name
      Description: Delete car
      FunctionVersion: '2018-05-29'
      Name: deletecar
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
  CreateCarResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
      TypeName: Mutation
      FieldName: createCar
      Kind: PIPELINE
      PipelineConfig:
        Functions:
        - Fn::GetAtt:
          - CreateCarFunction
          - FunctionId
      RequestMappingTemplate: '{}'
      ResponseMappingTemplate: $util.toJson($context.result)
  UpdateCarResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
      TypeName: Mutation
      FieldName: updateCar
      Kind: PIPELINE
      PipelineConfig:
        Functions:
        - Fn::GetAtt:
          - UpdateCarFunction
          - FunctionId
      RequestMappingTemplate: '{}'
      ResponseMappingTemplate: $util.toJson($context.result)
  GetCarResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
      TypeName: Query
      FieldName: getCar
      Kind: PIPELINE
      PipelineConfig:
        Functions:
        - Fn::GetAtt:
          - GetCarFunction
          - FunctionId
      RequestMappingTemplate: '{}'
      ResponseMappingTemplate: $util.toJson($context.result)
  ListCarResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
      TypeName: Query
      FieldName: getAllCars
      Kind: PIPELINE
      PipelineConfig:
        Functions:
        - Fn::GetAtt:
          - ListCarFunction
          - FunctionId
      RequestMappingTemplate: '{}'
      ResponseMappingTemplate: $util.toJson($context.result)
  DeleteCarResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt:
        - CarApi
        - ApiId
      TypeName: Mutation
      FieldName: deleteCar
      Kind: PIPELINE
      PipelineConfig:
        Functions:
        - Fn::GetAtt:
          - DeleteCarFunction
          - FunctionId
      RequestMappingTemplate: '{}'
      ResponseMappingTemplate: $util.toJson($context.result)
  DynamoDBPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: DirectAppSyncLambda
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: dynamodb:*
          Resource:
          - Fn::GetAtt:
            - CarTable
            - Arn
      Roles:
      - Ref: AppSyncServiceRole
