version = 0.1
[default.deploy.parameters]
stack_name = "car-app"
resolve_s3 = true
s3_prefix = "car-app"
region = "us-east-1"
profile = "educloud"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"dev\" TechStack=\"graphql\" UserPoolId=\"us-east-1_LLFLvrw8a\" UserPoolIdRegion=\"us-east-1\""
image_repositories = []
