version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "carMergedApi"
s3_prefix = "carMergedApi"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"stage\" TechStack=\"graphqlapi\" UserPoolId=\"us-east-2_HREKK4JXw\" UserPoolIdRegion=\"us-east-2\""
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-w7fazjv91dr3"

